<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'title',
                'slug' => 'عنوان الموقع',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 0,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'title',
                'slug' => 'Website Title',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 0,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'site_keys',
                'slug' => 'الكلمات المفتاحية للموقع',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 99,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'site_keys',
                'slug' => 'Keywords',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 99,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'site_desc',
                'slug' => 'وصف الموقع',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 100,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'site_desc',
                'slug' => 'description',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 100,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'website_status',
                'slug' => 'حالة الموقع',
                'value' => '1',
                'type' => 'select',
                'lang' => 'ar',
                'isOption' => 1,
                'options' => 'مغلق,متاح',
                'sort_number' => 1,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2018-11-19 09:37:29',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'website_status',
                'slug' => 'Website status',
                'value' => '1',
                'type' => 'select',
                'lang' => 'en',
                'isOption' => 1,
                'options' => 'closed,open',
                'sort_number' => 1,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2018-11-19 08:05:55',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'closed_msg',
                'slug' => 'محتوى صفحة غلق الموقع',
                'value' => '<p>الموقع مغلق للصيانه</p>',
                'type' => 'editor',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 2,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2018-09-30 13:30:42',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'closed_msg',
                'slug' => 'Content of closing the website',
                'value' => '<p>0</p>',
                'type' => 'editor',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 2,
                'created_at' => '2018-08-30 00:00:00',
                'updated_at' => '2018-11-19 08:05:55',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'header',
                'slug' => 'اضافة فى الهدير',
                'value' => NULL,
                'type' => 'script',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 20,
                'created_at' => '2018-09-17 00:00:00',
                'updated_at' => '2018-10-01 14:08:57',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'header',
                'slug' => 'Add in head',
                'value' => NULL,
                'type' => 'script',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 20,
                'created_at' => '2018-09-17 00:00:00',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'footer',
                'slug' => 'إضافة فى الفوتر',
                'value' => '',
                'type' => 'script',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 21,
                'created_at' => '2018-09-17 00:00:00',
                'updated_at' => '2019-07-29 21:52:57',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'footer',
                'slug' => 'Add in footer ',
                'value' => NULL,
                'type' => 'script',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 21,
                'created_at' => '2018-09-17 00:00:00',
                'updated_at' => '2019-07-29 22:13:58',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'site_word_content',
                'slug' => 'الكلمة الرئيسية للموقع',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 3,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'site_word_content',
                'slug' => 'Main website word',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 3,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-07-02 12:06:25',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'site_footer_content',
                'slug' => 'محتوى نبذة الموقع فى الفوتر',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 4,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-07-02 12:06:25',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'site_footer_content',
                'slug' => 'Footer Content',
                'value' => NULL,
                'type' => 'textarea',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 4,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-07-02 12:06:25',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'site_address',
                'slug' => 'العنوان',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 5,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'site_phone',
                'slug' => 'ارقام التلفونات',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 7,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            20 => 
            array (
                'id' => 23,
                'name' => 'site_phone',
                'slug' => 'Phones',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 7,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            21 => 
            array (
                'id' => 24,
                'name' => 'site_address',
                'slug' => 'address',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 5,
                'created_at' => '2018-09-30 00:00:00',
                'updated_at' => '2019-10-27 08:43:23',
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'site_email',
                'slug' => 'البريد الالكترونى',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 9,
                'created_at' => '2018-11-19 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            23 => 
            array (
                'id' => 26,
                'name' => 'site_email',
                'slug' => 'E-mail address',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 9,
                'created_at' => '2018-11-19 00:00:00',
                'updated_at' => '2019-10-27 08:43:24',
            ),
            24 => 
            array (
                'id' => 27,
                'name' => 'our_goal',
                'slug' => 'هدفنا',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 22,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            25 => 
            array (
                'id' => 28,
                'name' => 'our_goal',
                'slug' => 'Our Goal',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 22,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            26 => 
            array (
                'id' => 29,
                'name' => 'our_policy',
                'slug' => 'سياستنا',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 23,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            27 => 
            array (
                'id' => 30,
                'name' => 'our_policy',
                'slug' => 'Our Policy',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 23,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            28 => 
            array (
                'id' => 31,
                'name' => 'our_mession',
                'slug' => 'مهمتنا',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 24,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            29 => 
            array (
                'id' => 32,
                'name' => 'our_mession',
                'slug' => 'Our mession',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 24,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            30 => 
            array (
                'id' => 33,
                'name' => 'advantages',
                'slug' => 'مميزات',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => '',
                'sort_number' => 25,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            31 => 
            array (
                'id' => 34,
                'name' => 'advantages',
                'slug' => 'advantages',
                'value' => NULL,
                'type' => 'layouts',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 25,
                'created_at' => '2018-11-21 00:00:00',
                'updated_at' => '2019-10-27 08:43:56',
            ),
            32 => 
            array (
                'id' => 37,
                'name' => 'thankspage',
                'slug' => 'Default thanks page',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'en',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-10-27 11:39:32',
            ),
            33 => 
            array (
                'id' => 38,
                'name' => 'thankspage',
                'slug' => 'عنوان صفحه الشكر الافتراضيه',
                'value' => NULL,
                'type' => 'text',
                'lang' => 'ar',
                'isOption' => 0,
                'options' => NULL,
                'sort_number' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-10-27 08:43:24',
            ),
        ));
        
        
    }
}